# -*- coding: utf-8 -*-
"""CheckPoint_CyberV2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/felps2003/checkPoint_Cyber/blob/main/CheckPoint_CyberV2.ipynb
"""

!pip install -q streamlit

!pip install -q streamlit-ace

!pip install -q pyngrok

!pip install -q fuzzywuzzy[speedup]

from fuzzywuzzy import process

!streamlit run app.py &>/dev/null&

# Commented out IPython magic to ensure Python compatibility.
 %%writefile app.py
 import streamlit as st
 import re
 import json
 import requests as req
 from fuzzywuzzy import process
 from fuzzywuzzy import fuzz
 from pyngrok import ngrok

 res = req.get('https://felps2003.github.io/irq.json')
 res = requests.get('https://henricobela.github.io/fra.json')
 nomes = req.get('https://cspinheiro.github.io/interpol.json')

 def verificarNome(names):
   nome = nomes.json()['interpol']
   lista_fuzzy = []
   extraidos = process.extract(names, nome)

   for i in extraidos:
     if i[1] >= 74:
       lista_fuzzy.append(i)
     if len(lista_fuzzy) == 0:
       return 'permitido'
     return 'nao_permitido'

 def verificacaoPassaporte(numPassaporte):
   match = re.search('(?i)(\D{3})', numPassaporte.lower())
   api = str(match[0])
   paises = ['irq','fra']
   if api in paises:
     x = str(api)
     dict_api = res.json()[x]
     for item in dict_api:
       for value in item.values():
         if str(numPassaporte) == str(x)+str(value):
           return 'invalido'
         return 'valido'


 def main():

   html_temp = """ <div style ="background-color:red;padding:15px">
                       <h1 style = "color:black;text-align:center;">Verificador Imigração Internacional</h1>
                       <h6 style = "color:white;text-align:center;">Por favor insira as 3 letras principais do pais, mais os numeros do passaporte</h6>
                   </dic>
               """

   st.markdown(html_temp, unsafe_allow_html = True)

   names = st.text_input('nome da pessoa: ')
   numPassaporte = st.text_input('Passaporte: ')
   if st.button("Verificar"):
     def verificacao(names,numPassaporte):
      imigrante = verificarNome(names)
      passaporte = verificacaoPassaporte(numPassaporte)

      if passaporte == 'invalido' or imigrante == 'nao_permitido':
        st.error('Prenda o individuo')
        return
      st.success('Pode entrar no país')
      return



 if __name__=='__main__':
     main()

!streamlit run app.py & npx localtunnel --port 8501